### ISSUE TITLE
Android 8 Support

### ISSUE THREAD

**Issue by SparkyNZ** [foundryzero/binder-trace#20]
Hi. Could we please have the structs for Android 8. I'm trying to give this a go on an older device that's having binder leaking issues. Would be much appreciated. Thank you. I've tried using -a 9 and -a10 with the device but it shows no Binder activity at all, so I'm guessing its the Android version that's the problem.

**Comment by sam-f0** [comment]
The structs for Android 8 have been added to the repo, however they have not been tested.
