### ISSUE TITLE
Catching transactions on application launch

### ISSUE THREAD

**Issue by kay-22** [foundryzero/binder-trace#29]
Is it possible to launch the app after I attach? I want to catch the transactions when I launch my app, but I could only attach after I launch the app, so I miss those transactions at the start.

**Comment by sam-f0** [comment]
Thanks for the feature request. We'll look to get this implemented in the next major version release.

**Comment by sam-f0** [comment]
Sorry for the delay getting this feature released, it is now in version 1.4.0
