### ISSUE TITLE
Structs information

### ISSUE THREAD

**Issue by wss-14** [foundryzero/binder-trace#38]
How can I find\get structs information of a specific mobile phone？

**Comment by sam-f0** [comment]
Structs are generated from the AOSP source code - we are currently unable to generate struct information for mobile device manufacturer specific changes to their ROMs where source code is not published.

**Comment by wss-14** [comment]
If I get the source code, how can I generate such structs? Any tools exists? Thanks so much

**Comment by sam-f0** [comment]
Some more information on the struct format can be found https://github.com/foundryzero/binder-trace/blob/main/STRUCTURES.md

There are no current plans for the release of a tool to generate them, sorry.
