### ISSUE TITLE
How to make struct file from android?

### ISSUE THREAD

**Issue by backahasten** [foundryzero/binder-trace#9]
May I ask what tool or method you used to extract the binder structure from Android？

**Comment by N1rv0us** [comment]
@sam-f0 
I found that the TRANSCATION_CODE in my device is different from the one defined in the struct file. I had to adjust the definitions in the struct file to ensure that the results were correct.
Would you please update the definition of the struct interfaces in the future ?

**Comment by madushan1000** [comment]
@sam-f0 can you include android 14 structs? I'm using `android-14.0.0_r28` but any android 14 tag would work. thank you.

**Comment by sam-f0** [comment]
@madushan1000 I will endeavor to generate them and push a new version this week

**Comment by madushan1000** [comment]
Thank you :) any plans to open source the struct generator? I'm playing around with adding new aidl apis and I've been hand writing some struct files. Good enough for small apis but not that great for functions with complex types/custom parcelebles.

**Comment by sam-f0** [comment]
@madushan1000 binder-trace 3.1.2 has been released with the Android 14 structures from `android-14.0.0_r28`

There are no current plans to open source the generator, as per my prior comment https://github.com/foundryzero/binder-trace/issues/9#issuecomment-1584657286

**Comment by madushan1000** [comment]
Okay, thank you for the update, I'll try it out :)

**Comment by sam-f0** [comment]
We have added some more information about struct files in release 1.4.0 in https://github.com/foundryzero/binder-trace/blob/main/STRUCTURES.md
